server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

endpoints:
  base-url: /api/personas
  filtros:
    porNombre: /filtro-porNombre
    porEdad: /filtro-porEdad
    porGenero: /filtro-porGenero

logging:
  level:
    root: INFO